<?php

declare(strict_types=1);

/*
 * This file is part of the ALTO library.
 *
 * © 2026-present Simon André
 *
 * For full copyright and license information, please see
 * the LICENSE file distributed with this source code.
 */

return [
    [
        'id' => 'php',
        'name' => 'PHP',
        'category' => 'Programming',
        'extension' => 'php',
        'source' => 'languages/php.php',
        'featured' => true,
        'notes' => 'Definitions, calls, types, variables, and interpolated strings.',
    ],
    [
        'id' => 'html',
        'name' => 'HTML',
        'category' => 'Markup',
        'extension' => 'html',
        'source' => 'languages/html.html',
        'featured' => true,
        'notes' => 'Document structure, elements, attributes, and embedded content.',
    ],
    [
        'id' => 'svg',
        'name' => 'SVG',
        'category' => 'Markup',
        'extension' => 'svg',
        'source' => 'languages/svg.svg',
        'featured' => false,
        'notes' => 'XML-based vector elements, attributes, definitions, and colors.',
    ],
    [
        'id' => 'xml',
        'name' => 'XML',
        'category' => 'Markup',
        'extension' => 'xml',
        'source' => 'languages/xml.xml',
        'featured' => false,
        'notes' => 'Declarations, namespaces, nested elements, and attributes.',
    ],
    [
        'id' => 'yaml',
        'name' => 'YAML',
        'category' => 'Data',
        'extension' => 'yaml',
        'source' => 'languages/yaml.yaml',
        'featured' => false,
        'notes' => 'Mappings, sequences, booleans, flow collections, and strings.',
    ],
    [
        'id' => 'sql',
        'name' => 'SQL',
        'category' => 'Data',
        'extension' => 'sql',
        'source' => 'languages/sql.sql',
        'featured' => false,
        'notes' => 'Common table expressions, joins, functions, and ordering.',
    ],
    [
        'id' => 'json',
        'name' => 'JSON',
        'category' => 'Data',
        'extension' => 'json',
        'source' => 'languages/json.json',
        'featured' => false,
        'notes' => 'Objects, arrays, strings, booleans, and nested values.',
    ],
    [
        'id' => 'css',
        'name' => 'CSS',
        'category' => 'Stylesheet',
        'extension' => 'css',
        'source' => 'languages/css.css',
        'featured' => true,
        'notes' => 'Custom properties, selectors, functions, and layout declarations.',
    ],
    [
        'id' => 'scss',
        'name' => 'SCSS',
        'category' => 'Stylesheet',
        'extension' => 'scss',
        'source' => 'languages/scss.scss',
        'featured' => false,
        'notes' => 'Variables, nested selectors, functions, and media queries.',
    ],
    [
        'id' => 'markdown',
        'name' => 'Markdown',
        'category' => 'Markup',
        'extension' => 'md',
        'source' => 'languages/markdown.md',
        'featured' => false,
        'notes' => 'Headings, emphasis, inline code, lists, quotes, and fenced code.',
    ],
    [
        'id' => 'javascript',
        'name' => 'JavaScript',
        'category' => 'Programming',
        'extension' => 'js',
        'source' => 'languages/javascript.js',
        'featured' => true,
        'notes' => 'Destructuring, array methods, loops, templates, and exports.',
    ],
    [
        'id' => 'typescript',
        'name' => 'TypeScript',
        'category' => 'Programming',
        'extension' => 'ts',
        'source' => 'languages/typescript.ts',
        'featured' => false,
        'notes' => 'Interfaces, typed arrays, predicates, functions, and exports.',
    ],
    [
        'id' => 'twig',
        'name' => 'Twig',
        'category' => 'Templating',
        'extension' => 'twig',
        'source' => 'languages/twig.twig',
        'featured' => true,
        'notes' => 'Inheritance, blocks, filters, loops, output, and embedded HTML.',
    ],
    [
        'id' => 'makefile',
        'name' => 'Makefile',
        'category' => 'Build',
        'extension' => 'mk',
        'source' => 'languages/makefile.mk',
        'featured' => false,
        'notes' => 'Variables, functions, phony targets, prerequisites, and recipes.',
    ],
    [
        'id' => 'bash',
        'name' => 'Bash',
        'category' => 'Shell',
        'extension' => 'sh',
        'source' => 'languages/bash.sh',
        'featured' => false,
        'notes' => 'Shebangs, strict mode, arrays, loops, expansions, and redirects.',
    ],
    [
        'id' => 'ini',
        'name' => 'INI',
        'category' => 'Configuration',
        'extension' => 'ini',
        'source' => 'languages/ini.ini',
        'featured' => false,
        'notes' => 'Sections, keys, strings, booleans, numbers, and file paths.',
    ],
    [
        'id' => 'http',
        'name' => 'HTTP',
        'category' => 'Protocol',
        'extension' => 'http',
        'source' => 'languages/http.http',
        'featured' => false,
        'notes' => 'Request lines, headers, body separation, and JSON payloads.',
    ],
    [
        'id' => 'go',
        'name' => 'Go',
        'category' => 'Programming',
        'extension' => 'go',
        'source' => 'languages/go.go',
        'featured' => false,
        'notes' => 'Packages, imports, constants, structs, methods, and calls.',
    ],
    [
        'id' => 'rust',
        'name' => 'Rust',
        'category' => 'Programming',
        'extension' => 'rs',
        'source' => 'languages/rust.rs',
        'featured' => false,
        'notes' => 'Structs, references, options, inferred values, and macros.',
    ],
    [
        'id' => 'ruby',
        'name' => 'Ruby',
        'category' => 'Programming',
        'extension' => 'rb',
        'source' => 'languages/ruby.rb',
        'featured' => false,
        'notes' => 'Data classes, symbols, arrays, blocks, interpolation, and calls.',
    ],
    [
        'id' => 'swift',
        'name' => 'Swift',
        'category' => 'Programming',
        'extension' => 'swift',
        'source' => 'languages/swift.swift',
        'featured' => false,
        'notes' => 'Structs, typed properties, computed values, arrays, and loops.',
    ],
    [
        'id' => 'python',
        'name' => 'Python',
        'category' => 'Programming',
        'extension' => 'py',
        'source' => 'languages/python.py',
        'featured' => false,
        'notes' => 'Imports, decorators, data classes, annotations, loops, and f-strings.',
    ],
    [
        'id' => 'java',
        'name' => 'Java',
        'category' => 'Programming',
        'extension' => 'java',
        'source' => 'languages/java.java',
        'featured' => false,
        'notes' => 'Packages, records, classes, typed methods, streams, and references.',
    ],
    [
        'id' => 'csharp',
        'name' => 'C#',
        'category' => 'Programming',
        'extension' => 'cs',
        'source' => 'languages/csharp.cs',
        'featured' => false,
        'notes' => 'Usings, records, inferred arrays, LINQ, loops, and interpolation.',
    ],
    [
        'id' => 'dockerfile',
        'name' => 'Dockerfile',
        'category' => 'Build',
        'extension' => 'Dockerfile',
        'source' => 'languages/dockerfile.Dockerfile',
        'featured' => false,
        'notes' => 'Multi-stage builds, copies, work directories, runs, and commands.',
    ],
    [
        'id' => 'diff',
        'name' => 'Diff',
        'category' => 'Change',
        'extension' => 'diff',
        'source' => 'languages/diff.diff',
        'featured' => false,
        'notes' => 'Git headers, file markers, hunk ranges, context, and additions.',
    ],
    [
        'id' => 'dotenv',
        'name' => 'dotenv',
        'category' => 'Configuration',
        'extension' => 'env',
        'source' => 'languages/dotenv.env',
        'featured' => false,
        'notes' => 'Assignments, booleans, quoted values, URLs, and interpolation.',
    ],
];
